.PHONY: all data

all: data

data: compute_all_directional_spectra

compute_all_directional_spectra: ../_codes/compute_all_directional_spectra.py
	python3 ../_codes/compute_all_directional_spectra.py
